### ISSUE TITLE
Possibly no need for libffi / JNI?

### ISSUE THREAD

**Issue by den1k** [borkdude/datalevin-native#1]
I'm no expert on Java/JNI/GraalVM but wanted to see how deep the rabbit hole error of compiled binary goes since I was very excited about the possibility of running datalevin on devices like raspberry pi. Posting this issue for reference @huahaiy

So in:

```
$ ./datalevin-native
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.kenai.jffi.Foreign.invokeN1O1(JJJLjava/lang/Object;III)J [symbol: Java_com_kenai_jffi_Foreign_invokeN1O1 or Java_com_kenai_jffi_Foreign_invokeN1O1__JJJLjava_lang_Object_2III]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
...
```

the issue stems from lmdbjava using [jnr/ffi](https://github.com/jnr/jffi)
https://github.com/lmdbjava/lmdbjava/blob/165b3f7c0bfbbf02d81d0208b46f35d638f0d291/src/main/java/org/lmdbjava/Library.java#L40-L48

It might be possible to fix this by registering calls to native methods as described here:
https://github.com/oracle/graal/blob/master/substratevm/JNI.md

or to patch lmdb java and avoid JNI entirely: https://cornerwings.github.io/2018/07/graal-native-methods/

**Comment by huahaiy** [comment]
Interesting. Thanks for the pointers.

**Comment by huahaiy** [comment]
FYI, Now the source tree of Datalevin contains a native version of Datalevin. I did this by writing some GraalVM specific code to wrap LMDB. Version 0.4.0 will include this feature.

**Comment by den1k** [comment]
@borkdude looks like this should work now!
