### ISSUE TITLE
lmdb native build

### ISSUE THREAD

**Issue by weiyongh** [borkdude/datalevin-native#3]
now I want to build a graal native image for lmdb. I see the lmdbjava native fork in your repositories. I have a question. that is can I build this fork version and run in native mode? I try but I met some troubles:

`Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.lmdbjava.ByteBufferProxy.<clinit>(ByteBufferProxy.java:70)
        at org.lmdbjava.Env.create(Env.java:87)
        at org.sample.Main.main(Main.java:25)
Caused by: org.lmdbjava.LmdbException: address not found
        at org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy.findField(ByteBufferProxy.java:168)
        at org.lmdbjava.ByteBufferProxy$ReflectiveProxy.<clinit>(ByteBufferProxy.java:221)
        ... 3 more`

here is my graal build command arguments:

`native-image.cmd -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace --no-fallback --initialize-at-run-time=org.lmdbjava.ByteBufferProxy,org.lmdbjava.Library,org.lmdbjava.ResultCodeMapper,org.lmdbjava.UnsafeAccess -jar lmdb-jar-with-dependencies.jar`

also a reflection file:

`[
  {
    "name": "org.lmdbjava.BufferProxy",
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "org.lmdbjava.ByteBufferProxy",
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "org.lmdbjava.Dbi",
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "org.lmdbjava.UnsafeAccess",
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy",
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "org.lmdbjava.ByteBufferProxy$ReflectiveProxy",
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "org.lmdbjava.Env",
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  }
]`

I also find that some code from datalevin. You write some code to wrap lmdb. Please give me some clues how I can build a seperate native lmdb. thanks.

**Comment by borkdude** [comment]
This project is no longer relevant since datalevin can already be compiled to native.
